name: flask test

on: push

jobs:
  build_flask:
    runs-on: ubuntu-latest
    steps:
      -
        name: show vars
        env:
          DCK_USER: ${{ vars.DOCKERHUB_USERNAME }}
          DCK_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo ${DCK_USER}
          echo ${DCK_PASS}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/flask-test:latest