name: flask aws test

on: push

jobs:
  build_flask:
    runs-on: ubuntu-latest
    steps:
      -
        name: show vars
        env:
          DCK_USER: ${{ secrets.AWS_ACCESS_KEY_ID }}
          DCK_PASS: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo ${DCK_USER}
          echo ${DCK_PASS}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 299391716392.dkr.ecr.sa-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 299391716392.dkr.ecr.sa-east-1.amazonaws.com/aws-lambda:flask-test