name: flask test

on: pull_request

jobs:
  build_flask:
    runs-on: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: install python
        run: |
          docker image build -tag test_flask .